ozil

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,8 +37,8 @@ jobs:
               run: npm ci
 
             # Prettier formatting
-            #- name: 'Code formatting verification with Prettier'
-             # run: npm run prettier:verify
+            - name: 'Code formatting verification with Prettier'
+              run: npm run prettier:verify
 
             # Lint LWC / Aura
             - name: 'Lint Lightning Web Components / Aura Components'
@@ -72,14 +72,20 @@ jobs:
             - name: 'Checkout source code'
               uses: actions/checkout@v2
 
-            # Authenticate dev hub
-            - name: 'Authenticate DevHub'
+            # Store secret for dev hub
+            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
               shell: bash
               run: |
-                echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
-                node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid "${{ secrets.SALESFORCE_CONSUMER_KEY }}" --jwtkeyfile server.key --username "${{ secrets.SALESFORCE_DEVHUB_USERNAME}}" --setdefaultdevhubusername -a devhub
-              env:
-                SALESFORCE_JWT_SECRET_KEY: "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}"
+                  echo "${{ secrets.DEVHUB_SFDX_URL}}" > ./DEVHUB_SFDX_URL.txt
+                  secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+                  if [ $secretFileSize == 1 ]; then
+                      echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+                      exit 1;
+                  fi
+
+            # Authenticate dev hub
+            - name: 'Authenticate Dev Hub'
+              run: sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d
 
             # Create scratch org
             - name: 'Create scratch org'
